pcx2raw2 asp1.pcx asp1.raw 80 200
binobj32 asp1.raw asp1.obj layer1

pcx2raw2 asp2.pcx asp2.raw 80 200
binobj32 asp2.raw asp2.obj layer2

pcx2raw2 asp3.pcx asp3.raw 80 200
binobj32 asp3.raw asp3.obj layer3

pcx2raw2 asp4.pcx asp4.raw 80 200
binobj32 asp4.raw asp4.obj layer4

pcx2raw2 asp5.pcx asp5.raw 80 200
binobj32 asp5.raw asp5.obj layer5

pcx2raw2 asp6.pcx asp6.raw 80 200
binobj32 asp6.raw asp6.obj layer6

pcx2raw2 vlogo1.pcx vlogo1.raw 320 50
binobj32 vlogo1.raw vlogo1.obj layer7

pcx2raw2 vlogo2.pcx vlogo2.raw 320 50
binobj32 vlogo2.raw vlogo2.obj layer8

