pcx2raw2 kiina1.pcx kiina1.raw 80 200
binobj32 kiina1.raw kiina1.obj layer1

pcx2raw2 kiina2.pcx kiina2.raw 80 200
binobj32 kiina2.raw kiina2.obj layer2

pcx2raw2 kiina3.pcx kiina3.raw 80 200
binobj32 kiina3.raw kiina3.obj layer3

pcx2raw2 kiina4.pcx kiina4.raw 80 200
binobj32 kiina4.raw kiina4.obj layer4

pcx2raw2 kiina5.pcx kiina5.raw 80 200
binobj32 kiina5.raw kiina5.obj layer5

pcx2raw2 kiina6.pcx kiina6.raw 80 200
binobj32 kiina6.raw kiina6.obj layer6

pcx2raw2 i3logo1.pcx i3logo1.raw 320 50
binobj32 i3logo1.raw i3logo1.obj layer7

pcx2raw2 i3logo2.pcx i3logo2.raw 320 50
binobj32 i3logo2.raw i3logo2.obj layer8

